BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[embeddings_tb] (
    [id] INT NOT NULL IDENTITY(1,1),
    [fileName] NVARCHAR(255) NOT NULL,
    [fileType] CHAR(1) NOT NULL,
    [fileData] VARBINARY(max) NOT NULL,
    [updatedAt] DATETIME2 NOT NULL CONSTRAINT [embeddings_tb_updatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [embeddings_tb_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
